apiVersion: v2
name: ingress-nginx
description: Ingress-Nginx

type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx